// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"business/business.mdx": () => import("../content/docs/business/business.mdx?collection=docs"), "business/cla.mdx": () => import("../content/docs/business/cla.mdx?collection=docs"), "business/license.mdx": () => import("../content/docs/business/license.mdx?collection=docs"), "backend/canvas-data-structure.mdx": () => import("../content/docs/backend/canvas-data-structure.mdx?collection=docs"), "backend/local-development.mdx": () => import("../content/docs/backend/local-development.mdx?collection=docs"), "canvas/canvas-node-manual.mdx": () => import("../content/docs/canvas/canvas-node-manual.mdx?collection=docs"), "canvas/canvas-shortcuts.mdx": () => import("../content/docs/canvas/canvas-shortcuts.mdx?collection=docs"), "overview/codex-app-plugin.mdx": () => import("../content/docs/overview/codex-app-plugin.mdx?collection=docs"), "overview/docker.mdx": () => import("../content/docs/overview/docker.mdx?collection=docs"), "overview/features.mdx": () => import("../content/docs/overview/features.mdx?collection=docs"), "overview/low-memory.mdx": () => import("../content/docs/overview/low-memory.mdx?collection=docs"), "overview/quick-start.mdx": () => import("../content/docs/overview/quick-start.mdx?collection=docs"), "overview/render.mdx": () => import("../content/docs/overview/render.mdx?collection=docs"), "overview/third-party-prompt-repositories.mdx": () => import("../content/docs/overview/third-party-prompt-repositories.mdx?collection=docs"), "progress/local-agent-integration-plan.mdx": () => import("../content/docs/progress/local-agent-integration-plan.mdx?collection=docs"), "progress/pending-test.mdx": () => import("../content/docs/progress/pending-test.mdx?collection=docs"), "progress/todo.mdx": () => import("../content/docs/progress/todo.mdx?collection=docs"), "support/donate.mdx": () => import("../content/docs/support/donate.mdx?collection=docs"), "support/security.mdx": () => import("../content/docs/support/security.mdx?collection=docs"), "support/sponsor.mdx": () => import("../content/docs/support/sponsor.mdx?collection=docs"), }),
};
export default browserCollections;